language: c
before_script: ./autogen.sh
compile:
    - clang
    - gcc
branches:
    only:
        - master
before_install:
    - sudo apt-get install -qq autotools-dev autoconf automake pkg-config libtool
script: ./configure && make && make -j 4 check 
